---
version: 2.1

master_filter: &master_filter
  filters:
    tags:
      ignore: /.*/
    branches:
      only:
        - master

workflows:
  version: 2
  ci:
    jobs:
      - build
      - test-influxdb:
          matrix:
            parameters:
              version: ["2.0", "2.1"]
      - publish_docker_images:
          <<: *master_filter

jobs:
  build:
    docker:
      - image: cimg/go:1.15.6
    steps:
      - checkout
      - setup_remote_docker
      - run: bash circle-test.sh

  test-influxdb:
    machine: true
    parameters:
      version:
        type: string
        enum: ["2.0", "2.1"]
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get install -y jq
      - run: bash influxdb/test/test-2x-e2e.sh << parameters.version >>
      - store_artifacts:
          path: influxdb/test/logs
          destination: container-logs

  publish_docker_images:
    docker:
      - image: 'cimg/python:3.6'
    steps:
      - checkout
      - run:
          name: Install Prerequisite Packages
          command: |
            sudo bash -s \<<EOF
              #!/bin/bash
              set -o errexit  \
                  -o nounset  \
                  -o pipefail

              export DEBIAN_FRONTEND=noninteractive
              apt-get update
              apt-get install --yes git
            EOF

            python3 -m pip install -r \
              .circleci/scripts/update_manifest_file/requirements.txt
      - run:
          name: Get Enterprise Information
          command: |
            python3 .circleci/scripts/get_enterprise_info
      - run:
          name: Do Enterprise Release
          command: |
            .circleci/scripts/do-enterprise-release
